// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgqxUz2KNltOHR2LpFqbC4-Cb0WxYKB4',
    appId: '1:160699198852:web:44285bb3b2dd22e71241d1',
    messagingSenderId: '160699198852',
    projectId: 'redit-clone-c9ba1',
    authDomain: 'redit-clone-c9ba1.firebaseapp.com',
    storageBucket: 'redit-clone-c9ba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGd6RnV3b1pOTGcgBzCpHoCoKyvJeQpo',
    appId: '1:160699198852:android:34dff000bfe757041241d1',
    messagingSenderId: '160699198852',
    projectId: 'redit-clone-c9ba1',
    storageBucket: 'redit-clone-c9ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgJ-r8h6Ih8C-LWFaRc7iOZnDOpJPY6E',
    appId: '1:160699198852:ios:69fb88412cf6e57c1241d1',
    messagingSenderId: '160699198852',
    projectId: 'redit-clone-c9ba1',
    storageBucket: 'redit-clone-c9ba1.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgJ-r8h6Ih8C-LWFaRc7iOZnDOpJPY6E',
    appId: '1:160699198852:ios:69fb88412cf6e57c1241d1',
    messagingSenderId: '160699198852',
    projectId: 'redit-clone-c9ba1',
    storageBucket: 'redit-clone-c9ba1.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
